apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podcustomizers.gr1nx.dev
spec:
  group: gr1nx.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                promote:
                  type: boolean
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                  format: int64
                numPromoted:
                  type: integer
                numDestroyed:
                  type: integer
                targetPod:
                  type: string
                targetNamespace:
                  type: string
  names:
    kind: PodCustomizer
    plural: podcustomizers
  scope: Namespaced
